## Experiment on Chapter 02 - Problem #3 

### First Case

$
\newline
\boldsymbol{y} = \begin{bmatrix}
y_1\\
y_2\\
...\\
y_d
\end{bmatrix} \quad
X = \begin{bmatrix}
1 & x_1\\
1 & x_2\\
... & ...\\
1 & x_d
\end{bmatrix} \quad 
\boldsymbol{\phi} = \begin{bmatrix}
\phi_0 & \phi_1
\end{bmatrix} 
$

$\text{Such that}$

$
y = X\boldsymbol{\phi}^T
$

and 

$
X = y\boldsymbol{\phi}(\boldsymbol{\phi}^T\boldsymbol{\phi})^{-1}
$

In [38]:
import numpy as np

total_average_err = []

dataset_size = 1000
num_iter = 10

for i in range(0, num_iter):
    x = np.random.rand(dataset_size, 2).astype(np.float64)
    x[:,0] = x[:,0] * 0 + 1
    w = np.random.rand(1,2).astype(np.float64)
    y = x @ w.T
    w_outer = w.T @ w
    
    x_recovered = (y @ w @ (np.linalg.inv(w_outer)))
    mse_error = np.mean((x - x_recovered)**2)
    total_average_err.append(mse_error)

print('Case #1 Error: ', np.max(total_average_err))

Case #1 Error:  68738.35115097645



### Second Case

$
\newline
\boldsymbol{y} = \begin{bmatrix}
y_1\\
y_2\\
...\\
y_d
\end{bmatrix} \quad
X = \begin{bmatrix}
0 & x_1\\
0 & x_2\\
... & ...\\
0 & x_d
\end{bmatrix} \quad 
\boldsymbol{\phi} = \begin{bmatrix}
\phi_0 & \phi_1
\end{bmatrix} 
$

$\text{Such that}$

$
y = X\boldsymbol{\phi}^T
$

and 

$
X = y\boldsymbol{\phi}(\boldsymbol{\phi}^T\boldsymbol{\phi})^{-1}
$

In [89]:
total_average_err = []

dataset_size = 1000
for i in range(0, 1000):
    x = np.random.rand(dataset_size, 2).astype(np.float64)
    x[:,0] = x[:,0] * 0 
    w = np.random.rand(1,2).astype(np.float64)
    y = x @ w.T
    x_recovered = (y @ w @ (np.linalg.inv(w.T @ w)))
    mse_error = np.mean((x - x_recovered)**2)
    total_average_err.append(mse_error)
    # print(mse_error)

print('Case #2 Error: ', np.mean(total_average_err))

Case #1 Error:  2474.8239698956695



### Third Case

$
\newline
\boldsymbol{y} = \begin{bmatrix}
y_1\\
y_2\\
...\\
y_d
\end{bmatrix} \quad
X = \begin{bmatrix}
0 & x_1\\
0 & x_2\\
... & ...\\
0 & x_d
\end{bmatrix} \quad 
$

$\text{Such that}$

$
y = X{\phi_1} + {\phi}_0 
$

$
X = (y - \phi_0)/\phi_1
$

Obviously, this should work

In [91]:
total_average_err = []

dataset_size = 1000
for i in range(0, 1000):
    x = np.random.rand(dataset_size, 1).astype(np.float64)
    w1 = np.random.rand(1).astype(np.float64)
    w0 = np.random.rand(1).astype(np.float64)
    y = x * w1 + w0
    x_recovered = (y - w0) / w1  
    mse_error = np.mean((x - x_recovered)**2)
    total_average_err.append(mse_error)
    # print(mse_error)

print('Case #2 Error: ', np.mean(total_average_err))

Case #2 Error:  7.620414933703757e-27


### Additional Investigation

In [27]:
import numpy as np
import matplotlib.pyplot as plt

total_average_err = []
total_inv_err = []
w_outer_invs = []

dataset_size = 1000
num_iter = 10

x = np.random.rand(dataset_size, 2).astype(np.float64)
x[:,0] = x[:,0] * 0 + 1
w = np.random.rand(1,2).astype(np.float64)
y = x @ w.T
w_outer = w.T @ w

w_outer_inv_v1 = np.linalg.inv(w_outer)
w_outer_inv_v2 = np.linalg.inv(w_outer)

print('w_outer = \n', w_outer)
print('w_outer_inv_v1 = \n', w_outer_inv_v1)
print('w_outer_inv_v2 = \n', w_outer_inv_v2)
print('w_outer_inv_v1 - w_outer_inv_v2 = \n', np.abs(w_outer_inv_v1 - w_outer_inv_v2))

w_outer = 
 [[0.24689861 0.27880346]
 [0.27880346 0.31483115]]
w_outer_inv_v1 = 
 [[ 4.73287840e+16 -4.19127174e+16]
 [-4.19127174e+16  3.71164381e+16]]
w_outer_inv_v2 = 
 [[ 4.73287840e+16 -4.19127174e+16]
 [-4.19127174e+16  3.71164381e+16]]
w_outer_inv_v1 - w_outer_inv_v2 = 
 [[0. 0.]
 [0. 0.]]


```
w_outer_inv_v1 = 
 [[ 4.73287840e+16 -4.19127174e+16]
 [-4.19127174e+16  3.71164381e+16]]
w_outer_inv_v2 = 
 [[ 4.73287840e+16 -4.19127174e+16]
 [-4.19127174e+16  3.71164381e+16]]
```

### Concluding Remarks
- Errors happening in **Case #1** and **Case #2** are attributed by large values of the inverse with magnitude ~$10^{16}$